###########
# site.title

title:    'The Man Cave'
subtitle: 'Barber shop located in Bellvue, PA'


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
