###########
# site.title

title:    'Jekyll Starter Theme V2'
subtitle: 'Another Static Site Quick Starter Theme'


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
